import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FCF9F2",
  },
  mainContent: {
    paddingHorizontal: 24,
    paddingVertical: 40,
    width: "100%",
    maxWidth: 1024,
    alignSelf: "center",
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  pageTitle: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#1e3a5f",
  },
  clearButton: {
    backgroundColor: "#fcd34d",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  clearButtonText: {
    fontWeight: "bold",
    color: "#1e3a5f",
  },
  cartList: {
    gap: 16,
    marginBottom: 24,
  },
  cartCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  cartCardLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  productImage: {
    width: 96,
    height: 96,
    borderRadius: 12,
  },
  productInfo: {
    justifyContent: "center",
  },
  productName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1e3a5f",
    marginBottom: 4,
  },
  productPriceDay: {
    fontSize: 14,
    color: "#6b7280",
    marginBottom: 8,
  },
  dateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dateText: {
    fontSize: 13,
    color: "#8ba6d1",
    fontWeight: "500",
  },
  cartCardRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  subtotalContainer: {
    alignItems: "flex-end",
  },
  subtotalLabel: {
    color: "#6b7280",
    fontSize: 14,
    marginBottom: 4,
  },
  subtotalValue: {
    color: "#ef4444",
    fontWeight: "bold",
    fontSize: 20,
  },
  removeButton: {
    backgroundColor: "#ef4444",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    justifyContent: "center",
    marginLeft: 8,
  },
  removeButtonText: {
    color: "#ffffff",
    fontWeight: "bold",
    fontSize: 14,
  },
  emptyCartCard: {
    backgroundColor: "#ffffff48",
    borderRadius: 16,
    paddingVertical: 48,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 1, height: 3 },
    shadowOpacity: 0.2,
    width: "100%",
    maxWidth: 600,
    alignSelf: "center",
    marginTop: 20,
  },
  emptyCartText: {
    fontSize: 16,
    color: "#64748b",
    marginBottom: 20,
    textAlign: "center",
    fontWeight: "500",
  },
  emptyCartButton: {
    backgroundColor: "#fcd34d",
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 12,
    marginVertical: 20,
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
  },
  emptyCartButtonText: {
    color: "#1e3a8a",
    fontWeight: "bold",
    fontSize: 16,
  },
  totalCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 24,
    marginTop: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  totalLabel: {
    textAlign: "center",
    color: "#6b7280",
    fontSize: 14,
    marginBottom: 8,
    fontWeight: "500",
  },
  totalValue: {
    textAlign: "center",
    fontSize: 40,
    fontWeight: "bold",
    color: "#10b981",
    marginBottom: 24,
  },
  proceedButton: {
    backgroundColor: "#ef4444",
    paddingVertical: 16,
    borderRadius: 12,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  proceedButtonText: {
    color: "#ffffff",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 18,
  },
});
