import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8faff",
  },
  mainContent: {
    paddingHorizontal: 16,
    paddingVertical: 20,
    width: "100%",
    maxWidth: 700,
    alignSelf: "center",
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: "#1e3a8a",
  },
  clearButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fee2e2",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#fecaca",
  },
  clearButtonText: {
    fontWeight: "700",
    fontSize: 12,
    color: "#ef4444",
    marginLeft: 4,
  },
  addressCard: {
    backgroundColor: "#eff6ff",
    borderColor: "#bfdbfe",
    borderWidth: 1.5,
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  addressHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  addressTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#1e3a8a",
    marginLeft: 6,
  },
  addressText: {
    fontSize: 13,
    color: "#374151",
    fontWeight: "700",
    lineHeight: 18,
  },
  addressSubtext: {
    fontSize: 12,
    color: "#6b7280",
    marginTop: 2,
  },
  addressPeriod: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#dbeafe",
  },
  addressPeriodText: {
    fontSize: 11,
    color: "#4b5563",
    fontWeight: "600",
    marginLeft: 4,
  },
  cartList: {
    marginBottom: 20,
  },
  cartCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    shadowColor: "#1e3a8a",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cartCardTop: {
    flexDirection: "row",
    alignItems: "center",
  },
  productImage: {
    width: 65,
    height: 65,
    borderRadius: 10,
    marginRight: 12,
    backgroundColor: "#f3f4f6",
  },
  productInfo: {
    flex: 1,
    justifyContent: "center",
  },
  productName: {
    fontSize: 14,
    fontWeight: "800",
    color: "#1f2937",
    marginBottom: 3,
  },
  productPriceDay: {
    fontSize: 12,
    color: "#6b7280",
    marginBottom: 3,
    fontWeight: "500",
  },
  dateRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  dateText: {
    fontSize: 11,
    color: "#3b6fd4",
    fontWeight: "600",
    marginLeft: 4,
  },
  divider: {
    height: 1,
    backgroundColor: "#f3f4f6",
    marginVertical: 10,
  },
  cartCardBottom: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  subtotalContainer: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  subtotalLabel: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "500",
  },
  subtotalValue: {
    color: "#1e3a8a",
    fontWeight: "800",
    fontSize: 15,
  },
  removeButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fef2f2",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#fee2e2",
  },
  removeButtonText: {
    color: "#ef4444",
    fontWeight: "700",
    fontSize: 11,
    marginLeft: 4,
  },
  emptyCartCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    paddingVertical: 45,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
    marginTop: 20,
  },
  emptyCartText: {
    fontSize: 15,
    color: "#6b7280",
    marginVertical: 14,
    textAlign: "center",
    fontWeight: "600",
  },
  emptyCartButton: {
    backgroundColor: "#1e3a8a",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
  },
  emptyCartButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 14,
  },
  totalCard: {
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 16,
    shadowColor: "#1e3a8a",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  totalLabel: {
    color: "#6b7280",
    fontSize: 14,
    fontWeight: "700",
  },
  totalValue: {
    fontSize: 22,
    fontWeight: "900",
    color: "#10b981",
  },
  proceedButtonWrapper: {
    borderRadius: 14,
    overflow: "hidden",
  },
  proceedButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
  },
  proceedButtonText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 15,
  },
});