import { StyleSheet } from "react-native";


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FCF9F2",
    paddingBottom: 20,
  },
  searchSection: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    marginHorizontal: 16,
    marginVertical: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E6F4FE",
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 14,
    color: "#333",
  },
  categoriesScroll: {
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  categoryButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 8,
    borderRadius: 20,
    backgroundColor: "#E6F4FE",
    borderWidth: 1,
    borderColor: "#8ba6d1",
  },
  categoryButtonActive: {
    backgroundColor: "#1e3a5f",
    borderColor: "#1e3a5f",
  },
  categoryText: {
    fontSize: 12,
    color: "#1e3a5f",
    fontWeight: "600",
  },
  categoryTextActive: {
    color: "#fff",
  },
  toysGrid: {
    paddingHorizontal: 12,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  toyCard: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 12,
    marginBottom: 16,
    overflow: "hidden",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  toyImage: {
    width: "100%",
    height: 120,
    backgroundColor: "#E6F4FE",
  },
  toyInfo: {
    padding: 12,
  },
  toyName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1e3a5f",
    marginBottom: 4,
  },
  toyDescription: {
    fontSize: 11,
    color: "#666",
    marginBottom: 8,
  },
  toyFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  toyPrice: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FF6B6B",
  },
  toyCapacity: {
    fontSize: 10,
    color: "#8ba6d1",
    marginTop: 2,
  },
  addButton: {
    padding: 4,
  },
  emptyState: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 14,
    color: "#999",
    marginTop: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    flex: 1,
    backgroundColor: "#FCF9F2",
    marginTop: 40,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E6F4FE",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1e3a5f",
    flex: 1,
    textAlign: "center",
    marginHorizontal: 8,
  },
  modalBody: {
    flex: 1,
    paddingHorizontal: 16,
  },
  modalImage: {
    width: "100%",
    height: 200,
    marginVertical: 12,
    borderRadius: 12,
  },
  toyDetailsContainer: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  detailsTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1e3a5f",
    marginBottom: 12,
  },
  detailRow: {
    marginBottom: 10,
  },
  detailLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#666",
  },
  detailValue: {
    fontSize: 12,
    color: "#333",
    marginTop: 2,
  },
  priceContainer: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#E6F4FE",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  priceLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#333",
  },
  priceValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FF6B6B",
  },
  calendarSection: {
    marginBottom: 20,
  },
  calendarTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1e3a5f",
    marginBottom: 12,
  },
  datesSummary: {
    backgroundColor: "#E6F4FE",
    borderRadius: 12,
    padding: 12,
    marginTop: 12,
  },
  datesSummaryText: {
    fontSize: 12,
    color: "#333",
    fontWeight: "600",
  },
  daysText: {
    fontSize: 12,
    color: "#666",
    marginTop: 4,
  },
  totalPrice: {
    fontSize: 14,
    fontWeight: "700",
    color: "#FF6B6B",
    marginTop: 6,
  },
  addToCartButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FF6B6B",
    marginHorizontal: 16,
    marginBottom: 16,
    paddingVertical: 14,
    borderRadius: 12,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  addToCartButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
    marginLeft: 8,
  },
});
