import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8faff",
  },

  // === HERO BANNER ===
  heroBanner: {
    paddingTop: 24,
    paddingBottom: 32,
    paddingHorizontal: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  heroContent: {
    flex: 1,
  },
  heroBadge: {
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 4,
    alignSelf: "flex-start",
    marginBottom: 12,
  },
  heroBadgeText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  heroTitle: {
    fontSize: 26,
    fontWeight: "900",
    color: "#fff",
    lineHeight: 32,
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  heroSubtitle: {
    fontSize: 12,
    color: "rgba(255,255,255,0.85)",
    lineHeight: 18,
    marginBottom: 20,
  },
  heroStats: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 12,
    padding: 12,
  },
  statItem: {
    alignItems: "center",
    flex: 1,
  },
  statNumber: {
    fontSize: 14,
    fontWeight: "800",
    color: "#fff",
  },
  statLabel: {
    fontSize: 10,
    color: "rgba(255,255,255,0.75)",
    marginTop: 2,
  },
  statDivider: {
    width: 1,
    height: 24,
    backgroundColor: "rgba(255,255,255,0.3)",
  },
  heroBalloons: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 8,
  },
  balloonEmoji: {
    fontSize: 32,
  },

  // === SEARCH ===
  searchWrapper: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "#f8faff",
  },
  searchSection: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#e5e7eb",
    shadowColor: "#1e3a8a",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  searchFocused: {
    borderColor: "#3b6fd4",
    shadowOpacity: 0.12,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 14,
    color: "#111827",
    fontWeight: "500",
  },

  // === CATEGORIES ===
  categoriesScroll: {
    marginBottom: 4,
  },
  categoriesContent: {
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  categoryButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#fff",
    borderWidth: 1.5,
    borderColor: "#e5e7eb",
    marginRight: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  categoryButtonActive: {
    backgroundColor: "#1e3a8a",
    borderColor: "#1e3a8a",
  },
  categoryIcon: {
    fontSize: 14,
    marginRight: 5,
  },
  categoryText: {
    fontSize: 12,
    color: "#4b5563",
    fontWeight: "600",
  },
  categoryTextActive: {
    color: "#fff",
  },

  // === SECTIONS ===
  section: {
    marginTop: 20,
    paddingHorizontal: 16,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: "#111827",
    letterSpacing: -0.3,
  },
  sectionSubtitle: {
    fontSize: 12,
    color: "#9ca3af",
    fontWeight: "500",
  },

  // === FEATURED ===
  featuredScroll: {
    paddingRight: 4,
  },
  featuredCard: {
    width: 280,
    height: 190,
    borderRadius: 18,
    overflow: "hidden",
    marginRight: 12,
    shadowColor: "#1e3a8a",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 6,
  },
  featuredImage: {
    width: "100%",
    height: "100%",
  },
  featuredGradient: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "65%",
    padding: 14,
    justifyContent: "flex-end",
  },
  featuredBadge: {
    backgroundColor: "#f97316",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: "flex-start",
    marginBottom: 6,
  },
  featuredBadgeText: {
    color: "#fff",
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  featuredName: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 6,
    lineHeight: 22,
  },
  featuredFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  featuredPrice: {
    color: "#fbbf24",
    fontSize: 14,
    fontWeight: "800",
  },
  featuredPeople: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 10,
    paddingHorizontal: 7,
    paddingVertical: 3,
  },
  featuredPeopleText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "600",
  },

  // === TOY CARDS GRID ===
  toysGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  toyCard: {
    width: "48%",
    backgroundColor: "#fff",
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 14,
    shadowColor: "#1e3a8a",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  toyImageContainer: {
    position: "relative",
  },
  toyImage: {
    width: "100%",
    height: 130,
    backgroundColor: "#f0f4ff",
  },
  toyIconBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    backgroundColor: "rgba(255,255,255,0.95)",
    borderRadius: 12,
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  toyIconText: {
    fontSize: 15,
  },
  toyInfo: {
    padding: 11,
  },
  toyName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 4,
    lineHeight: 18,
  },
  toyDescription: {
    fontSize: 11,
    color: "#6b7280",
    lineHeight: 16,
    marginBottom: 7,
  },
  toyMeta: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  toyMetaText: {
    fontSize: 10,
    color: "#6b7280",
    fontWeight: "500",
  },
  toyFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  toyPriceLabel: {
    fontSize: 9,
    color: "#9ca3af",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  toyPrice: {
    fontSize: 15,
    fontWeight: "800",
    color: "#1e3a8a",
    lineHeight: 20,
  },
  toyPriceDay: {
    fontSize: 9,
    color: "#6b7280",
    fontWeight: "500",
  },
  addButton: {
    borderRadius: 12,
    overflow: "hidden",
  },
  addButtonGradient: {
    width: 34,
    height: 34,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },

  // === EMPTY STATE ===
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 50,
    paddingHorizontal: 24,
  },
  emptyEmoji: {
    fontSize: 52,
    marginBottom: 12,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#374151",
    marginBottom: 6,
  },
  emptySubtitle: {
    fontSize: 13,
    color: "#9ca3af",
    textAlign: "center",
    lineHeight: 19,
    marginBottom: 20,
  },
  clearFilterButton: {
    backgroundColor: "#1e3a8a",
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  clearFilterText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "700",
  },

  // === MODAL ===
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.55)",
  },
  modalContent: {
    backgroundColor: "#f8faff",
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: "92%",
    overflow: "hidden",
  },
  modalImageContainer: {
    position: "relative",
    height: 280,
  },
  modalImage: {
    width: "100%",
    height: "100%",
  },
  modalImageGradient: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "60%",
  },
  modalCloseButton: {
    position: "absolute",
    top: 14,
    right: 14,
    backgroundColor: "rgba(0,0,0,0.45)",
    borderRadius: 20,
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  modalTitleContainer: {
    position: "absolute",
    bottom: 14,
    left: 16,
    right: 16,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#fff",
    marginBottom: 6,
    lineHeight: 28,
  },
  modalPriceBadge: {
    backgroundColor: "#f97316",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: "flex-start",
  },
  modalPriceBadgeText: {
    color: "#fff",
    fontSize: 13,
    fontWeight: "800",
  },
  modalBody: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  modalDescription: {
    fontSize: 14,
    color: "#374151",
    lineHeight: 22,
    marginBottom: 16,
  },
  detailsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 20,
  },
  detailChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderWidth: 1,
    borderColor: "#e0e7ff",
    marginRight: 8,
    marginBottom: 8,
  },
  detailChipText: {
    fontSize: 11,
    color: "#374151",
    fontWeight: "600",
  },
  calendarSection: {
    marginBottom: 8,
  },
  calendarStepHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  stepDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#e5e7eb",
    alignItems: "center",
    justifyContent: "center",
  },
  stepDotDone: {
    backgroundColor: "#22c55e",
  },
  stepDotText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#fff",
  },
  calendarStepText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
    flex: 1,
  },
  resetDatesButton: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "center",
    marginTop: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  resetDatesText: {
    fontSize: 12,
    color: "#6b7280",
    fontWeight: "600",
  },
  summaryCard: {
    borderRadius: 16,
    padding: 16,
    marginTop: 14,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  summaryLabel: {
    fontSize: 11,
    color: "rgba(255,255,255,0.7)",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 3,
  },
  summaryValue: {
    fontSize: 13,
    color: "#fff",
    fontWeight: "700",
  },
  summaryDays: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.18)",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  summaryDaysNumber: {
    fontSize: 22,
    fontWeight: "900",
    color: "#fbbf24",
  },
  summaryDaysLabel: {
    fontSize: 10,
    color: "rgba(255,255,255,0.8)",
    fontWeight: "600",
  },
  summaryDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.2)",
    marginVertical: 12,
  },
  summaryTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  summaryTotalLabel: {
    fontSize: 13,
    color: "rgba(255,255,255,0.85)",
    fontWeight: "600",
  },
  summaryTotalValue: {
    fontSize: 22,
    fontWeight: "900",
    color: "#fbbf24",
  },
  modalFooter: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: "#f8faff",
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
  },
  addToCartButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    borderRadius: 16,
  },
  addToCartButtonText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: 0.3,
  },
});